server:
  port: 8080

indexing-settings:
  sites:
    - url: https://www.sendel.ru
      name: sendel.ru
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.nekorrektniysite.net
      name: Некорректный сайт
#    - url: https://www.skillbox.ru
#      name: Skillbox

spring:
  datasource:
    username: root
    password: root
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
#    hikari:
#      auto-commit: true

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        order_updates: true
#        generate_statistics: true
        jdbc:
          batch_versioned_data: true
          batch_size: 100

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false

#logging:
#  level:
#    root: WARN